{
 "title": "Tasmota Plug Usage",
 "description": "A dashboard that shows your home energy usage. Using Prometheus and Tasmota.",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": " Current Power Draw",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tasmota_active_power{}", "legendFormat": "active_power" },
    { "expr": "tasmota_current{}", "legendFormat": "current" }
   ]
  },
  {
   "title": " Average Power Draw",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(tasmota_active_power{}[$__range])",
     "legendFormat": "power"
    },
    {
     "expr": "avg_over_time(tasmota_current{}[$__range])",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "Today's Power Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(tasmota_energy_total[$__range])",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "Today's Power Cost",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(tasmota_energy_total[$__range]) * .1908",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "This Month Total Power Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(tasmota_energy_total[$__range])",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "Cost This Month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(tasmota_energy_total[$__range]) * .1908",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "Last Month Total Power Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(tasmota_energy_total[$__range])",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "Cost Last Month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(tasmota_energy_total[$__range]) * .1908",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": " Peak Power Draw",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(tasmota_active_power{}[$__range])",
     "legendFormat": "power"
    },
    {
     "expr": "max_over_time(tasmota_current{}[$__range])",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "Peak Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time(tasmota_voltage{}[$__range])",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "Peak Day Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time(tasmota_energy_today_total{}[$__range])",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "tasmota_active_power{}", "legendFormat": "{{ sensor }}" }
   ]
  },
  {
   "title": "Month Power Total",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(tasmota_energy_total[$__range])",
     "legendFormat": "{{ sensor }} "
    }
   ]
  },
  {
   "title": "Daily Power Usage ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    { "expr": "tasmota_energy_today_total{}", "legendFormat": "{{ sensor }}" }
   ]
  },
  {
   "title": "Power Spikes Past Week",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(tasmota_power[1h])", "legendFormat": " Rate of Power" }
   ]
  }
 ]
}