---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/apps.emqx.io/emqx_v2beta1.json
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
spec:
  image: public.ecr.aws/emqx/emqx:5.7.0
  config:
    data: |
      authentication {
        backend = "built_in_database"
        mechanism = "password_based"
        password_hash_algorithm {
            name = "bcrypt",
        }
        user_id_type = "username"
      }
      authorization {
        sources = [
          {
            type = built_in_database
            enable = true
          }
        ]
        no_match: "deny"
      }
  bootstrapAPIKeys:
    - secretRef:
        key:
          secretName: emqx-secret
          secretKey: X_EMQX_APIKEY_KEY
        secret:
          secretName: emqx-secret
          secretKey: X_EMQX_APIKEY_SECRET
  coreTemplate:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
  listenersServiceTemplate:
    metadata:
      annotations:
        coredns.io/hostname: emqx.${CLUSTER_DOMAIN}
      labels:
        expose-bgp: "true"
    spec:
      type: LoadBalancer
