---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: onedev
  namespace: flux-system
spec:
  interval: 1h
  url: https://dl.cloudsmith.io/public/onedev/onedev/helm/charts
