---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &app mqtt2prometheus
  namespace: observability
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mqtt2prometheus-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yaml: |
          mqtt:
            server: tcp://mosquitto.database.svc.cluster.local:1883
            user: {{ .MOSQUITTO_USER }}
            password: {{ .MOSQUITTO_PASS }}
            topic_path: tele/+/SENSOR
            device_id_regex: ".*/(?P<deviceid>.*)/.*"
            qos: 0

          cache:
            timeout: 10m

          json_parsing:
            separator: .

          metrics:
            - prom_name: tasmota_active_power
              mqtt_name: ENERGY.Power
              help: Tasmota active power reading
              type: gauge

            - prom_name: tasmota_apparent_power
              mqtt_name: ENERGY.ApparentPower
              help: Tasmota apparent power reading
              type: gauge

            - prom_name: tasmota_reactive_power
              mqtt_name: ENERGY.ReactivePower
              help: Tasmota reactive power reading
              type: gauge

            - prom_name: tasmota_power_factor
              mqtt_name: ENERGY.Factor
              help: Tasmota power factor reading
              type: gauge

            - prom_name: tasmota_voltage
              mqtt_name: ENERGY.Voltage
              help: Tasmota voltage reading
              type: gauge

            - prom_name: tasmota_current
              mqtt_name: ENERGY.Current
              help: Tasmota current reading
              type: gauge

            - prom_name: tasmota_power_factor
              mqtt_name: ENERGY.Factor
              help: Tasmota power factor reading
              type: gauge

            - prom_name: tasmota_energy_today
              mqtt_name: ENERGY.Today
              help: Tasmota today's kWh usage
              type: gauge

            - prom_name: tasmota_energy_today
              mqtt_name: ENERGY.Today
              help: Tasmota today's kWh usage
              type: count

            - prom_name: tasmota_energy_yesterday
              mqtt_name: ENERGY.Yesterday
              help: Tasmota yesterday's kWh usage
              type: count

            - prom_name: tasmota_energy_total
              mqtt_name: ENERGY.Total
              help: Tasmota total kWh usage
              type: count

  dataFrom:
    - extract:
        key: mosquitto
