---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mqtt2prometheus
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: uninstall
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 65539
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      mqtt2prometheus:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            supplementalGroups:
              - 65542

        containers:
          app:
            image:
              repository: ghcr.io/hikhvar/mqtt2prometheus
              tag: v0.1.7

    service:
      app:
        controller: *app
        ports:
          metrics:
            port: 9641

    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 2m
            scrapeTimeout: 10s

    persistence:
      config:
        type: secret
        name: mqtt2prometheus-secret
        globalMounts:
          - path: /config.yaml
            subPath: config.yaml
