---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jellyfin
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      jellyfin:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            runAsNonRoot: true
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65542

        containers:
          app:
            image:
              repository: jellyfin/jellyfin
              tag: 10.10.3
            env:
              PUID: 2000
              PGID: 2000
              TZ: ${TIMEZONE}
              JELLYFIN_PublishedServerUrl: https://jellyfin.${CLUSTER_DOMAIN}
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [65542]
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        controller: *app
        ports:
          http:
            port: 8096

    ingress:
      app:
        className: cilium
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
          gethomepage.dev/description: Media Player
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Apps
          gethomepage.dev/icon: jellyfin
          gethomepage.dev/name: Jellyfin
        hosts:
          - host: &host jellyfin.${CLUSTER_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: jellyfin-tls-certificate

    persistence:
      config:
        existingClaim: jellyfin
        globalMounts:
          - path: /config
      media:
        type: nfs
        server: elysium.${STORAGE_DOMAIN}
        path: /export/media
        globalMounts:
          - path: /media
