apiVersion: v1
kind: Secret
metadata:
    name: onepassword-token
stringData:
    token: ENC[AES256_GCM,data:eKhPi5UyPyZI4bse/MF8xg0AqUZe6G+lRaRCRNuBandi+W4rXNn7bun3qa51nyxCaNA1bRlaUpjWQ/gfjch47p4Jm+XG6Fi1SkUtkwEKqVJK40ZKd+IIw7JVToDejaINoM9x6rhIT+jiZTGQ/IG55b/1rEJnTfw0udX017/tYxx0Ec0m83uor3TwPlvqpdT+QoC+lpXVI9OjjNRP9C6o5J1l/fatHTO/gz4kR2KaEb7z1zrAU99WqbB/s8f+aA6NZDEUJnU8eC4CPXtqO3Na8nmJOlsNeJGDQtpRlAm5VnN3+RJz+ZFYUqUi9lxa4+QhFBV/Dtbqn6q2Z/ZQTmFnCBEYjKIu4xopnADRXTC7TftgJPWQDclpOUoIlrpCRkLRbWuyA7uJ7kZZexeHKSoqZu9QeRYWejgtbz7DgwAbmxj7ClaHGkdwFMYknIkFw8pc3PYyGRIzBN+dsTzuDO/217l1IhVGQ6swoRJJ2rxTEj8x+oe1N9fVquTmeJk/hS8aJIX7L5uOLlSs7DYTFcjLBfa3Q1rb9QcCiEVRaOTttsJfruF2zdgGTMARZRd3SChPCCOmaKwTwP0l9j27CiLdPHAilxMmuOx+3ektB2U/ceSX3XISN4aqekorKrlrbH+oSc8dY27ArrAb5rcayN7ogu5ahKPTK/O4VSe4jqf/dPITSVQNk2KNbA8y625QZdk8UTxVP217q7naz7hHrrLa6XMNUO1eOQU5Jq7MlwCtukXzuW/Dz6xJT92QtGMBepaNQvy8pXmO7WmotAsaCqWmLXgAZma6SpqGZDIhbpU7d7gPx052uL4ZioemDRS2bZND2skZ3NDFKUi9KYHHxvyBz6E4,iv:XzRraWbZPA009x6quLzvny919gDZXrYkurQTT2LLmxw=,tag:OjfpfXlV2b23liHJhdC4eA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kl8w06hq4gdg3sutffnnu2nwwjx969p3ll2wguc6aqwpf8f8ny0sq6ztqx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQa3JQZjRTMVZGRkEzQXM1
            NkY3ZWtIbmZpUExSRjc0Z29ZUXV0YjdDaDJnCktwSnFnYitTUmRmY2xtWGVKWm9S
            VzAwanozTUFYR2kzYTNNWGNxQU1MaWcKLS0tIDVGSlJBTFZuQjNhb0JzNGlFMlV0
            MlVJbGN1Mi9rdnA3R2R4ejFabjVheHMK+kT4ozdBWLsJYzrryAr9Qt1EZIpN8ki8
            bGvMqtMUC9062L4IuK2dXfQ0S0GZAMvhs5FvcDWnVX54bktdruC5gA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-22T22:18:06Z"
    mac: ENC[AES256_GCM,data:otR/XlhH9TkHXn3trXwH1muDs3warqGVpdtf4Uec4Im/FH8+ZK4yUvQybTfeEu5aVX9AFBQ0C923v+8LS4uA4MwznrQVoZt4yqJn+DrACMkE8i/no2vNiVPLsLwx7Otu0ru3qwSro8d2rO0F37Zu/+Z/LE7/nxtmSuo+KWvO36U=,iv:suPYn7lNgDPHz84LnnPhTK3yjGYKb3rX7GpREekr+G8=,tag:M58nv7qaYvO0+TpqOlOtOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
