apiVersion: v1
kind: Secret
metadata:
    name: onepassword-token
stringData:
    token: ENC[AES256_GCM,data:RxK6bO4kGpnsOJOoYtRAWmQC+iiWYHlsP9mvibihRB2/6nax+KhAIkWYkI6QVFOnPJxdJiqzXUTm7yFRj+VmDcfr8vnKbh5bQ9aoKtakBuq4j5REb00ddI/s2LNpyaKAxXup0BS0ARflQtxfhnSx9EL45oguS9KV95TUbFLurkHOKWhTcvFRJIq9Ozew3H/jpO9KqwoeN+eQRtHNmkXaISUzmHpGKzTu/KAVJNFgEVmfpyCa/XHgYeI0AVFt5BCjpdi0rRqqskUfI9ulJjjnAA8JzLCxiwvDqQD46w+o+raC5D8EZIOtsc0xZfnpPcBEGFUoT/Ev/7Cd6Khf3GvcYWQaJRp+nFUTJcEiCdWM4i/OYSKcLqU6DowqPLsYmyUaXKaRGCMyC8FReLVNR50CgM/dj7NfWmXxNurHt5zHovBFu4Wt8qfa1OnhYdaFF6FHLrtTBjU5shJDbMSSpQZ9WB1rUwGMne0oqlgJQcF6PJO3zi/oPE3mpbYlPTvstIlVLXICz3YyoHqKNrPbebeAtBc0SOqElk2NCeOsI/7QGMuDbb7OHtMDzYQUW9DWVMQcT/BT8qI3v5h/7saNncY/JsGGpe+y6UWhPrBKqruX/W1o3pX5BLYsyV6HHq/Y26SCjKIS3YC1L3UcxfjA3CnqUImdS3gHEaxJpQBCcfvimdkt851Xn6GTYiOG8bmb7ULQhfmKIsk/VitRhyV+LDe5lq1c6GmmmxyymqiwDLzffDedCkyyUJ+s5aLFtd/yoUiKWEeyMhWQJUkGmAKiDWWDncU1eZEqvwmQycHmn4JgUgusAHHWwFsyEWcbMB3gnDlhj3l2/tRAK9bYL7xtcx6Rubbo,iv:OmVIPHxpB5F1/TA7CRwuCVrHt2YTODNCPecerafRbgM=,tag:HGr50Ph+MjbqL5V+TJExvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kl8w06hq4gdg3sutffnnu2nwwjx969p3ll2wguc6aqwpf8f8ny0sq6ztqx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrODBKbUhCejNzTzZ3SDNS
            dC8yMytPYkpLcTFVTWp2aGVCbXNna1FITWs0CmVSOXFyN0JXYkwzUWRUaEU4eTND
            aDM0RGVvcVpIYms5VFpqYmRjL3JNSlkKLS0tIHlZYmZvZFdsbnpVaE9LRkVHWWZv
            cUdxcUVvNDJnS2psQUZxeDFnNXZvQUEKMSNDbovQ/8EKUivaM+PflRLDiqhu5w3v
            Cuvcc5nHhzVEkche/p3HrnnZePeX/Y0nKPEYD1EP0tvelDQRqRgDpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-21T21:11:48Z"
    mac: ENC[AES256_GCM,data:eamktpCqNT1+72UexPJMgXzwiui1bwiP7YQJJpXRq5h3YCjditv1V6xE9iv1Zol6XCXGNMySO7fDN7YjP8ASuAITS7if3K7qHd853bOYNjd8l9+Z6QnREToxDv3QQ5XxfsdD4TK2BHpVvIc7FJZ3GTYd/zQqUbllRZJkwf4vY+o=,iv:NqFdh9ZQzHjAPTjhLi+M5cM+uGo6iQuo2oDfncaZtH0=,tag:2FnPI4S2NCEBTrs5wEdB2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
