apiVersion: v1
kind: Secret
metadata:
    name: op-credentials
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:wwvxyN43yHx2cM6Snvfm2tN6j8dleZf056HhhOJ+Qe9eBH2mKN7gjVtxLRuzjllGcgemgjgsLh7yqiJrSRKAL7CYnZUa/RPGydn8rkaTqvgKaDcvbnEMz8sRO68TdUBeYATceZ0UzGmaoFmr/tsoMreZb67MgvsxguY6ntG/ikzBvk91KQEcGI02GvKUvLk5EZLTydn5QmGh3utuSum4R0+g46jrIlLlM12HgJCLZ4osiqX75CeKd86pVABecgxkPnNVHaaBUyc9bdld6Qwpa1mQ/cb6fL9VAySFWv85CLwERtFXn1Hf26uSqPz8WRh02ti0w2rpyLhrWN8BFeR/CHZPNQeRhe1uoTt9vdiaZ8uX85hdI0ztHRGiSNsfWl2/genuFptHIMyVfdLL2Opb1Eiw1N3VNIeeh4exiS6xASzIFkOiVHV2dG2MoLyI/7vdla6gGR7o6yiVOd3Xso06grpW+McvPimP+CcVxQo4zcUBHxnp9rg1XQPyAlHxgSa5pbGvhERE5EnEnaegpHj+iN1LglAzra0/TGJ1ECBbKDq/yC2IyLOsvauHXMUBGRrPmGAgQeRIXxpoyJ36I/nDdXksa+/R+i4RZ7vsexXUCrRRClnr/MNfdQ9yaNTrarp2YjZ2ypn+hkwip0b5K0cfXE3b6vUXWJFQws9ybv/hsaA/4DSUBi4ZcvotH40OjtsixNyY9yLG3j/XiPVIDAVOFGIxxT3+TVqFfUCbhCgv6FHLSIUHSELiK12/LZkc7iD0JIdj4/Qs8vR2sOTqk1A9tiKYHGG7YNN1FgksmhbzhB6lKeQeO5PA6VzBgGdp/aDLSzhDPxPQ0B8KD6ujm2N0H6uim55UmFCeKyCowzjt/UsxeNK9PS5W9Mhfka0dn4CSbfcxK+CgV2hM0Fraf/tkEVZJ2VByMEAXIiJ4mxuBFtskfvFqhaiZPzU1fC+xEyRXUJP76ovncTcwPGUfYsla9KrY5myu8QVZQILZNBpb3olJxQYTXYocaJY7lFvp1vMIThBjiiuZfPydTMEL7WqBDuuIqvLbLTKtbNflBQYr4AiTI46K+obCJVitca0Cd31vYpt6HG1h12WjS8gN3b+HMYenQSlZz2Y6u5s9qO3UjKJGw8RWLXEMzvmQCL2GVO1oS84wuJqnYgnxrSROAmhgB+xaOJrlUMs03PpdwKUaEbh48uTbAYbKH/YKWvzoHT4AJHBhe2yip56ZZ8GuTEuKuA4oAxyThJZQ18oxSgqmya7D2nZU1g8jGR5ycFQqn7VHDVH3AxIUgJGA6oj9VYaHk3Zr+f1zCyq+wnYbKcaWiUHMM9YIgc823CJK5ewuYEAgQ11T8/f0oZDv0vNhfAB4THyDY+OwWd1NB4XWD1eAgTpgXuiuCWT8QEBxR9aRXFY9jERnP2l02R2nqqoqQZvkQjy3A5fkKtLDP0EkZjQq2bQ9R2DFzJYK1bVHLGpgcthbu9AOrkEjP5JZrsBIVaIGsGxodPe4pVRxTyOL6mP/2g9Yu1nt/NMd5oZeYsoMWEK+QNXyg6sr0MFJoGjragUIYtFXXBydMgKTAuL8mzsKI7ZHk+oddj5QcdJMeyPenhCEdj4JTgvHGKs28DrTpoZrw6IWB4o2p7f40TamojbS9OjwUFQFgvfAQoJ7vL5hx4KP8vKozoafyHy2uDNFw673fJdYITxldG3Rm6/j7cs0pf6mCuwAD+Rm9NT9KNJMMl8LnAvWQMmb8FlPbiik/OhRMxtiyexSpGWw9v4/ydlIi/9KN1EYbRnS3GEwhCjTdUjpeR1jO/fVyQZOBH8yWbCf2AsDChb1b2nxtx/XXHElsdF++0ZNL4O3YyMpdvTGdjg8nkmoSDjZNSL38n4iSif+XW5+h9TujI5qMqvRPGvFz3+Hpr8nqcpNNAbd4RSnZV/LDR2TLDd0zBRvKMoM,iv:mXdGBCNX603BmznFrayF04meXSQTnxyAlTqxg77uPkk=,tag:BooUaG7VMxshT718BjPF6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kl8w06hq4gdg3sutffnnu2nwwjx969p3ll2wguc6aqwpf8f8ny0sq6ztqx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZGhFQStCS2xYL3gxaitV
            dG53SzdPL3Mxay9Wd1V4Uy8raDNtc3BTb0V3Clg2QmxiU2JpNWxNNDhmK2ZwREh6
            QjJ4aW52VmZkYkFuN3ErL0dEM0ZqY0EKLS0tIFd0MzFINzc2anA1NTQ5ODR3NDhh
            Y0VuM01XNVM3TzlaVmFzaitGVVlwVFUKY8mNOKOxA1/p0A35CBP5GwKvBow5Mq4K
            1Jqu+Y//6BYkTfTGksEeT3CxAji3cr+u0UjrWqgj5wpWXxdqxPluMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-24T18:15:58Z"
    mac: ENC[AES256_GCM,data:3Kkc7nMiAOfuJNbEB3gXm/nO/2+aIYhjr+/CMkH5zGMyDcDwFQj1sIh0s5L2ZMdw7mCMakBszpG6Y73StacpV7gsYAx8gIlwcMskQP/WFinvvcFdorvre78QnzANWUCF5B9bjYEVPLMYKqnxtxATgIO+/bnJuRDcOCvyVD6mH9w=,iv:mLg55e6Ycv91/K40m4x0Y2ZnIhi3o/DyIFGXMqzTJzw=,tag:pHZgahD4iF6yndBoXRHSDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
