apiVersion: v1
kind: Secret
metadata:
    name: op-credentials
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:sgijjYinsDzNn2RHBJlxRGF/neoaOf/16gJsmDuK4b/FovYwg3NjOZjZmDgL+dXQ3DXIey2MXKck1NX9aQ19RZD5KyugG1uS0pjgK56VZ+bjBKC4mIzV2Z8eWD4Xo70EEwDXMzS3DZvE6h7xDzZoBwDHvk5S1zgHfgQskvb2G8iIY9NgEih8Bd4JBNKNUZyDC8Zjpd38wC+QfPTSWi6pepI5eMzfp5c6sGz/U1Avh2xo6uzNiAEaB8NvYXqxRbul/iDL60QQbsMQD6y4V5F2EWMgwjyBjJOGrFdjSHmAqDPTIyV/cGbwJxqrDP7MH9+ck2MR7I4xEzUM63UWY+1ne2xtu6CSd3jGWga5Lj14f5GZEyTzAr2uuz4LNAtI6J11d3WFpN44MA+Gm4JU/zWeq9t+3s+A2/364ztg5fGHZwMS4Zb2CUMIHVsLWNc0gt25JdI6voK19k0XvLc478kn0VciOrM8pimHZm0cRPJZG5dTHTFRj37dy76wEjGxInJvwqonCicFmsWpR/sm5Nw35mZYSK/uRn3nSytOXco2izbMgRQZUYpI+5AgjRz3F5CNPww7dYpyAAVO7JcAmq8EWzc+iG4f3ziakw+UeidLWUTKKLNIgCz70i3Q8C0vksiR4bHghT6PowGyaEygYjLC+kvFgcRsXZKhMmDBoFGEtbMLyFlQ3HAhMpKYlaCve1893iiUlj1cJOmkl3KH+ELAOtAZj6zIjy+gM76G1or/4IFAUHU3RcRZ59k1Pm5yru/ehPxWU9bdsP1U7lL+cOdGQMPAdTqWG7Ty0ZfX+ZcM9Q160/GIqw05E059ftcrlF6SK93inL40rwNkyZ2iHoQm1Sf+Zg5I6h9+WUjyXIX8vjrS0Z8s2XhNFz0fhk41VaecbB3auxRVKleMLVBPTwRin384uPT9sPibBBF/JFGL8FuopmaN38iXTsd3FykDfGD0CbPhtTOjYcqnHexgdOFpYHXsPXhbpAqnA4azfdMOj6ffj49HwNP7eeESTNZGlJWJahvonWv707o/YYiGNXYG+fiCqGfJhe+0kZ81FvPZgODeb09cTsGgvIXIQj3X353KUFV6TwaU1eBreLgM86HaUZXo7GP7tTSPqeHcm7WXehtfMgZEEDL9ZmIA8e6AQN8oNAN2i2B9RLY2USupIxJzooRL/epYfnTPasIM2GnbbveIvjHMONeBh3zfuxQDaYSekK/PSbFAGYipGE7A0mt7zsphP4zivtLgNokuqYxD8XB1A+uopACwyikfzNf3/lC2BKxqbuhpBYmN40aE9L5t+1nZxtH29hHMjdNijt1AmI1Xxi3pusWD7lyUGJnEWGjWmJDN8yCRfzeKAMCSXDZQNyDCogj59tbQ9nChTRjSveEj9trAzNBPzFIEglcvo5EcMv1T54HD4RGNimGWbsQGASGrRFigLei1e1RL4SG43yGoQz2RODb+++TFpHlmmLGmRV2czkD9Dsf9l+x3u5VZBKO17RSIP2G/ibpfLhwnK/llXopGuFETKmq5x+IKqzbAId3a6JCtLSI7bXQxs1LE4G2nrPX3HDlYSGmpBrGZq5nazaE7lkdQbcQ7VSlq2I7Eha7OIC3FElWZdyD+GqRJqTkkp7U67NQUuZ94d17cBRNQd5THbgZk8BEASAFKUKt4d1Zaydyvu2tkaT8kRArkjwZFzhufNkVmouC844ml+InmMnB2w2QBTXZFRDcDik1DE1HfFJ+Ms4jnNbBcK3dr1a4SqktTJd3b7Mss7jmeEzOyAFPFSdMwnGwFf0rfhO2Gt+gU4E7L6S/1fVe89a8lg/PfKVnUnRsKGiyXJgyEIKo0yAUcikjEe8mBTeQFrR6xDLygc9qjH4r72BXq4T15MrkNJ7iRoVoDy1WxDvBdfa/ONQcmnGxMsGJM+65ezMb+bpYxK/OwPu5BZUEs,iv:8g2BqabnL1WcqbdrERSizzxPdir/QDjsL3nRNhRGWgI=,tag:tvRz1LASvYazgwV+bkgyNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kl8w06hq4gdg3sutffnnu2nwwjx969p3ll2wguc6aqwpf8f8ny0sq6ztqx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZ3BIS0RtVVpYeFM0aXFU
            Tzg1a0tsMkZwRmRNc3gzRTkyVmJQZURVSkdNCnFIZHdEanNUbzhEYVJuTW1OYjJU
            L1FIS0V1MlZERkgrejMwN3ZnaXZuM1UKLS0tIGR1UDhMUW9nVHltNjVpN0NYTGla
            a1RoVW0xditTeXZ3c25CMHVySHM0OFkK3vgk+vO3Rl412+4l5Qx76ddmaomJ4Rl6
            gAxyRc89LjppB1de2Fyw9lQ7FLwmc+A7/B/4D2G5yBeNO2wX2b+M4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-25T12:38:52Z"
    mac: ENC[AES256_GCM,data:hlJ4JfitgegTtArlG5lFYVGQ9GF1GzjO9agI6eCXSzMbi3+ewMNjSBDPuWWGaBP79sIydr8rv130TuRNVGs2K5ZrKmpMTYomCsf/znRXzwtbjAHsi87eFshkiKKaeJ9J8ZIbQcVaU/tTjRV4XD2L1m8lJ3Xa4nRPUEXMUadDEpo=,iv:iz4F5kzx6mPMo+SEOaFfPagLdr6HXA/6C1kv7Va6rSE=,tag:CMiVqzGU3bdEuFe23wuMXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
