apiVersion: v1
kind: Secret
metadata:
    name: op-credentials
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:l+T9FuvEJbn/PTTcakhEgwu5N3NpWr0Y8+Tl+VPrv9Hb/0xTyi/6YUUhi1e2uBww3sRQimjXqsUNnCS6x2nCtfw/hrUYKgMzwt5Rb+TCm93tbWB7DzOQQSRyAsYY7V5KOHKUIwmuI4rgjgYi4If1DIhtVmUwKtlIywl+/zKD1ZEvNym8h9VdnUsHQviH46vnnLyNZNiQhVq06RBjoXE4BZoF3PdQ9d5O0o8wcn7apJZywIqPfrZg7aYqscYtsb9W+N/8q56EXBiAjpX3CCkdl/3VevR3smeFNYN0HBQpUv2NT3tLdUDFcCDnS2rwnf0lRQIdZ+bA50e5uXtqRS3bMV6PGT3jmNmsSyzD4Urx+aNpFQmBL4UhuORUryYJCeGbu6VfowtY9xnxAxYkXHX67XbO6hy60GAMoV8CQ9xd44JzYb3DDRQTI+/WJ8aRnSlh5V44cFs30hBtdvriFmkaOcIf8ssMK5pStVJ0K7n8hTP1TqAksfwvM50q+CSotMTFISxjDoedRLcBKYr5XE54Z5y+YhzXgrDPzQbdDTG/5G0bdKUKsN9EWJgSFsUFZ+Lg2ixQneLuOFtMg0EKtLfq/yb3wRuJSOmT6sazBATfRgs+BBFEyNiT2GKG+1Y2ExMjyC5uoG7bXC8YSw6O+J5iuxMU/AWoeLoeDN/+6gn29LUAHy81cjti2XfO2VsKX3/D8m2HpzdnX4BdAm4/9ehu+BdjQGZilJKeO4MC+g+1PFRquhqKaf7zZIOSIOYiNAz8wbBA3B0tgY+H9L5dsN1kDjSpxGC58qKw3D5D/tCyVGP/p7O3ZSY8BRj10LkKknJtY/mDxjrIc3J0C4JcPduWl0IqsntGGlNkvwcUAEOhDq6GE3CEJxPuIAo73CsI8X8A+e7PD0SqburacONwX71IlsZwezKS9yxTngb4dsn7qXhC5yP1DNSz8ykva//UcobIOn0hMPtehLZllQW2KngfIZSznFGd7+lF8H7XkdNlSvUGY0COMInyhTCQ7Jvfu35nmSOi9PczK0GmWiiElm/8Pgkda9Xb3nAGyCngEHnrYBo5eZ+P9YxpI2To/ioc0RHTz/5iOSQSADby2nJTOZlAefvYoyEN2/jq78rbrpNX75pipMVzc8RytegB3Y5fDaZwtPP99FTe/7sSfHSV1G7jqfDAQt+SBaKQusHsyt16/XAAyf2ZYKCw3lh7A22e28Rhfmed0UuNCbltk+qLCPQnaW70Xsv9X3CfyD5MAsLCacEtV+azWo+AnmkKT1n3lgXt9pRpJYPS3iNtJ72TkFOy1k9mveinTdJOXH11tBZM+mKeMk45WA6lNaiGaaURw5kTfvrYENiUyI7FZ3CFBioR/k1WjxCCCIsfKza+B5VbafBjNBfdtGrRlTKQk2mMwswgcGg7nFaklHrFBTMdW0r2wizUB0Q78IlFm2lkw7LLKPrak2Qbdq4YXX381mJeQrudhN5AwbQk0KF/EgJ+UyLYkkZPMETMGzzna1e+HQT0PemkQxWSMP5irLXIG9YCmmzHxBepRZbtClnQt0Lh20hEvcWDPlTVK4aNVW0SnNPzFNsFQ5znA4OjQFuV9arKpOpffksoJhQ4PHv5upTSAn2qDolq2ZXK49clQz+QAPGn1YuwTrUNYphCgikwrR96y9KWj3XZ54L1oVX4hrnLtCjXd6i33QgkRFXTKKAUVs5Rt0wsusYiFpie5r6ObgXKenJ5cz4bxow4L0E4UEmNzzNlc+8gpL3DxyKTSnOu9ABtVGrMmYdvkVdLggkcol9zdivkDe46lGpdeVSD06QUhb52lF1FcGk7c5/ipVfEDS40tBlH2VgND/Iww6MydK6yKLpt6gFctAtHpm16WR7nyyg38ePsauLctnFu4JW0ICUxQYJ0TYrhTVwMUQpBY3pmdZUU942PyYe0fMlhPpoj,iv:AAMm2SD8fZcl34CqEry5PTdyDah+KYScjrIJpYG/nL0=,tag:cj554W1K7hwSRRHmpDtZ5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kl8w06hq4gdg3sutffnnu2nwwjx969p3ll2wguc6aqwpf8f8ny0sq6ztqx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RU1Uc1hjazFzSG9WRnFs
            QkowdEtmNUFDRTJCQm5sMHNXbVdsY1FUOEhRCldiRGFQenBGUVJwOVgyM1BZNG5X
            RUZnTGdmYzN6bDV3UkVabSsyeWJtVWcKLS0tIENuWS81aUhsWE1nYitWeklGVkV3
            aGxrVXA0aERGUzZTL1kzdVN3c0MvWEkKDDodrtLkuy5yqetfYgvxh2cS5aFpOFZp
            QKEeN+77P1Z7amelJWzqwZRcuND9WUu0MJKhNcYRZHkvDpVOfDOvIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-21T21:11:48Z"
    mac: ENC[AES256_GCM,data:TNC9p9OTBI96+pqR3yOw8Ur3+rC++wBI6MuyYGVxI6+/kW7y58w/uSHFakoJQnWlocRpcVZx1mCnF+RhkLo2L0LzwHhdjwwrSwm6Fyx80D4LmAWHpYmDEZfyA8zilslZebcbymxXl+TgbTh/qdRu1zmfwvKwpX0zkB0BRY2kEhg=,iv:bQB78aa6o/nldq5BMu74QMBA8tRZCnM0yuiZr4ircas=,tag:PHN2JhaRVVtmJ7kfZsLVTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
