---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: emqx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: emqx-secret
    template:
      engineVersion: v2
      data:
        X_EMQX_APIKEY_KEY: "{{ .X_EMQX_APIKEY_KEY }}"
        X_EMQX_APIKEY_SECRET: "{{ .X_EMQX_APIKEY_SECRET }}"
  dataFrom:
    - extract:
        key: emqx
