---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wallos
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      wallos:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/ellite/wallos
              tag: 2.36.2@sha256:49919051a4c1e97eb263ec072a53eb15768667c3f5e258b9b228fedf8acf1c5a
            env:
              TZ: ${TIMEZONE}
            resources:
              requests:
                cpu: 50m
              limits:
                memory: 256Mi
 
    service:
      app:
        controller: *app
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        className: cilium
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
          gethomepage.dev/description: Subscriptions Tracker
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Apps
          gethomepage.dev/icon: wallos
          gethomepage.dev/name: Wallos
        hosts:
          - host: &host "wallos.${CLUSTER_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: wallos-tls-certificate
   
    persistence:
      config:
        existingClaim: wallos
        globalMounts:
          - path: /var/www/html/db
