---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wallos
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      wallos:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/ellite/wallos
              tag: 2.1.0@sha256:88f0af1e618fc910d2c135f284068f41ba9f357b08b7e9227cc9f43a047228b3
            env:
              TZ: ${TIMEZONE}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
              seccompProfile:
                type: RuntimeDefault
    service:
      app:
        controller: *app
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        className: cilium
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
          gethomepage.dev/description: Subscriptions Tracker
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Apps
          gethomepage.dev/icon: wallos
          gethomepage.dev/name: Wallos
        hosts:
          - host: &host "wallos.${CLUSTER_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: wallos-tls-certificate
    persistence:
      config:
        enabled: true
        storageClass: ceph-block
        globalMounts:
          - path: /var/www/html/db
        accessMode: ReadWriteOnce
        size: 1Gi
