---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app vector
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets-stores
  path: ./kubernetes/apps/observability/vector/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: winds
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  patches:
    - patch: |
        kind: Service
        apiVersion: v1
        metadata:
          name: vector-aggregator
          namespace: observability
          labels:
            expose-bgp: "true"
      target:
        kind: Service
        version: v1
        name: vector-aggregator
