---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: loki
      version: 6.6.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: Skip
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: vector-agent
      namespace: observability
    - name: vector-aggregator
      namespace: observability
  valuesFrom:
    - targetPath: loki.storage.bucketNames.chunks
      kind: ConfigMap
      name: &cephBucket loki-bucket
      valuesKey: BUCKET_NAME
    - targetPath: loki.storage.bucketNames.ruler
      kind: ConfigMap
      name: *cephBucket
      valuesKey: BUCKET_NAME
    - targetPath: loki.storage.bucketNames.admin
      kind: ConfigMap
      name: *cephBucket
      valuesKey: BUCKET_NAME
    - targetPath: loki.storage.s3.endpoint
      kind: ConfigMap
      name: *cephBucket
      valuesKey: BUCKET_HOST
    - targetPath: loki.storage.s3.accessKeyId
      kind: Secret
      name: *cephBucket
      valuesKey: AWS_ACCESS_KEY_ID
    - targetPath: loki.storage.s3.secretAccessKey
      kind: Secret
      name: *cephBucket
      valuesKey: AWS_SECRET_ACCESS_KEY
  values:
    loki:
      podAnnotations:
        configmap.reloader.stakater.com/reload: *cephBucket
        secret.reloader.stakater.com/reload: *cephBucket
      storage:
        type: s3
        s3:
          s3ForcePathStyle: true
          insecure: true
      auth_enabled: false
      memberlistConfig:
        bind_addr: []
        join_members:
          - loki-memberlist
      rulerConfig:
        enable_api: true
        enable_alertmanager_v2: true
        alertmanager_url: http://alertmanager-operated.observability.svc.cluster.local:9093
        storage:
          type: local
          local:
            directory: /rules
        rule_path: /rules/fake
      schemaConfig:
        configs:
          - from: "2024-04-01" # quote
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
    monitoring:
      dashboards:
        annotations:
          grafana_folder: Loki
      serviceMonitor:
        enabled: false
        metricsInstance:
          enabled: false
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
      lokiCanary:
        enabled: false
    test:
      enabled: false
    gateway:
      ingress:
        enabled: true
        ingressClassName: cilium
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
        hosts:
          - host: &host loki.${CLUSTER_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: loki-tls-certificate
    read:
      extraArgs:
        - -memberlist.bind-addr=$(MY_POD_IP)
      extraEnv:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
    write:
      extraArgs:
        - -memberlist.bind-addr=$(MY_POD_IP)
      extraEnv:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
    backend:
      extraArgs:
        - -memberlist.bind-addr=$(MY_POD_IP)
      extraEnv:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
