---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pg-superuser-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: cloudnative-pg
      property: username
  - secretKey: password
    remoteRef:
      key: cloudnative-pg
      property: password
