---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: onedev
spec:
  template:
    spec:
      containers:
        - name: onedevserver
          volumeMounts:
            - name: cacerts
              mountPath: /etc/ssl/certs/java/cacerts
              subPath: cacerts
      volumes:
        - name: cacerts
          secret:
          secretName: cacerts
