apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:xLb23IxZA4w2Ync=,iv:BxajFe17huye3n8CFmiuspi9vRxaAHuMNArDPOmzJDY=,tag:4T3A8//11TEuvJ44tCiJRA==,type:str]
    PHYSICAL_DOMAINL: ENC[AES256_GCM,data:9RBTHDPyHDixhpyO,iv:Vzh2FP+pi7T/m+n7U1MRQicho3CSZRpT51iw/KasZB8=,tag:0ajnAYfQZ5bAeiWY0VmhJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kl8w06hq4gdg3sutffnnu2nwwjx969p3ll2wguc6aqwpf8f8ny0sq6ztqx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVFpxSTJTQ3RaRDJqWmww
            TlpneG55RXQyUFpIZEhpRThlWkFWZXlPWVEwCjM1U1E0dUF1bEhDS1Q3bFlkWDRa
            L0M3Z01GQ1JoMHBCOG9wNFUxUHlUR2cKLS0tIG5GV1YwU0hxQitueVk0b2NoVVBk
            SFJ3c2lrMEMraUxMa3NPYytaTXpPWEkKvFhQ1zgCX8A7R4fj7oGHGDYfzuiTDwxH
            9qfR2VQ2lPqjG2gCs8kKFKYkK1FK6K+h9RaavPJwZ9RiYnKjVouCAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-25T18:46:28Z"
    mac: ENC[AES256_GCM,data:4aw6kVdi0KeNTFd5TKLZvqJlcHBPicwbbcsu1qLRd2vx3o8ZYisZwfbCzsaFH+RkF0iwBa5tvQOgqs+V0HLHxiB4a66MgXersoFtmvqnLw2sQldujwk5GXrgnl/Yo0/8BG5AN2hWPWgmlxQh7/x/YQ5wkxCucwnVMlSfqUEbvEE=,iv:GIDBC3qQpY9L7RYfQmZKkR0ahWpF8/ebWk8YPR2niSw=,tag:3K2PZQkWfhMDvkJuS7W4cw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
