apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:Iw+aKcaai7FiuJg=,iv:g3HKwUwsiEvwhE4OKawaL0h3gAgTpBWEJsWls6qU1tw=,tag:U9Goob0ciKBmJ4EvlLGraQ==,type:str]
    PHYSICAL_DOMAIN: ENC[AES256_GCM,data:pjiAdh9qsHm8NtXh,iv:LCeEl6aoGQssctzD2wb4LM6pvT0PsXyQLIL9CEQ/cMs=,tag:lwBeX6wcu8CR0YPiuQdvzA==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:Xh1Q6B4RNd3C7cgL,iv:yerfK/kLEx6o9GqCWWYJw/mBw6PhYAsDxApfq9T/nTs=,tag:ZD/g3aTWmL/EBEitpyV5Jg==,type:str]
    STORAGE_DOMAIN: ENC[AES256_GCM,data:guybjYx7brDhuLQ7WQ==,iv:eb8hQ3g2c/0ewrzBaxd3MA545lYZrWL6Dxrx/3lVklU=,tag:lG21YNIsxxBKaYl16C/d+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kl8w06hq4gdg3sutffnnu2nwwjx969p3ll2wguc6aqwpf8f8ny0sq6ztqx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2a2hIbFppY3YwNFU1OHFu
            NEthZDQxb3d2THZWUGhybWpMQklpUS94S0VvCllMQVdDMkJkNHVST0pnMi9CbjNX
            NG5GREI4NlNlSkFUdjhIZlA4WmhFb1EKLS0tIFlEWnA5WnQ1bndJRmN1Z1ZPU28r
            bHBHQ3Rtc0RuUEEwbTRRWUpqanpYK2sKq/oDBnSNuq37Dor6QgzsxcBpBUPPMBRx
            xUBHIwJyq34BMEFudGwznt/gcA4Zx0Pf6Nif3k0WLi+GD0vyWQZDDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-20T20:23:31Z"
    mac: ENC[AES256_GCM,data:HT9KJUf+0aQmmSs71EOEfoIXeXHa/qUDMal/sh86XcSTd+F7LGnmUGl06M/vTt4NXG0d/xSaTLmVyWEVCTeWy9uYKdADfXFGA6e4NC3f8dD442dT6WMBvUt4g3BURMhDfBT7OPrLNWTUdO9j+YZfXzmxetGcKJ0bBM+AX1iDLY0=,iv:5jmuUCznUuE83OfQN+BqQMwk5xtuvPiVdHDrUPAh4rg=,tag:SlEClp6k3Y002s36PcXwcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
