apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:2y0DB8i2wjDMpUo=,iv:/vFOXYRU8FjRM5s2VvV5ujKdVvo8b4fLcyzhHFj2bZk=,tag:wmIM2dqbxn62czVQY1SFuA==,type:str]
    PHYSICAL_DOMAINL: ENC[AES256_GCM,data:Fs5TgSMEfNs8sX/V,iv:QlficOAPQCrlq7mpsfI8BXr0LV2kkpCTxpWB95cOEGs=,tag:1eSsGlZK7TZ2JPOVbpx7pw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kl8w06hq4gdg3sutffnnu2nwwjx969p3ll2wguc6aqwpf8f8ny0sq6ztqx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVTdLL09KdDFXUStFTG05
            QS9VRkwrU2ZoUDVSVkRTc3pmdEo0dHNVV21FCkRKYmFFeU9YRFBkbTY0VTY5UDVj
            WjZTSDZRb1M0SzJ4cU5keUV0bHZKdTAKLS0tIGpqODFUcVNWK21scS9KV3YyZTFG
            SmdETVJTMjBXL25nclMxdUlYTjA5R1UKVwChtreRmoL9NChE3B2lTEAmlAqMWnlc
            Ev7FEkCkb/4a0DKubU8CHtM9fpT/xYavnR14qg/UUWf69zeHVpTNwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-22T22:18:06Z"
    mac: ENC[AES256_GCM,data:tlevThpKYxuliEsyt1vo5uYCOLnVJVxpxo2pymJ3R469A5aDDOZuhY+rjBJX/KIklyDuiSbqhCHssPKfGPH0nNrSt/Z3RMdhhmY+UOLfcOxnp2+EHHV1QzHpT5ASoVOHk3zs+jCG8vs3YbWRlrgQKKMbMJT34bsKhoEHRp9cksE=,iv:mLtZgB2on7lx+6IlL6kHfmc9B1gLxN+kplB36Io9w/M=,tag:H3cYCSWylGesydh0IYYlhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
