apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kl8w06hq4gdg3sutffnnu2nwwjx969p3ll2wguc6aqwpf8f8ny0sq6ztqx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRzJkV1RYWnNIQXZWdGN3
            QkFiV1FXYmtnWWJUR0F3RE00allUV0Q0eENJCnRYTFdDNXM2ZnVuVXBMT3hGNzBy
            TXhaMi85YXA3TmloR21LeW5XajJDakEKLS0tIEhSNWwyUzcyVWFuUDhZRTVvZ0VU
            N0Y3d096cWhuV2Eydjl6UDZBQTBGNTQKgFRtv1viSKuM7191jgHnfJK1KE5J7Oj7
            +2J2uKm8poK6H54b1JJ5dEHcisZ4psecjeZAlzQLZJI82EE5lCM5vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-30T22:24:15Z"
    mac: ENC[AES256_GCM,data:HsgSAdHyTCur/0cj1lRvvGVA2eL87mSTSlwr9kAD6JEcU6bOPly+GvQe24EE1qz0tU6JGFcG3ZAgzbWLHpr4DgdwoKp3FpCIaFFalnfSLtI+CKGATqiSJKbhu5rkQniMztvA01j/xC1VEYomxLJNBD+hEAKZ7F1N/avkX6PbW4I=,iv:Ci/hUZ3IZL06YeVTxNyjnQLEEasByQfolV0cyJZCetk=,tag:AbtiEskye/bZbNtTYw4IpQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
