apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:KZ7tiQq+McCRVOY=,iv:qIJTGLj1g6ttATMCgRuVacVHeARmB7wuVkxexMzaLiI=,tag:cQHV2e8hUI9SGu5lsFlEOA==,type:str]
    PHYSICAL_DOMAIN: ENC[AES256_GCM,data:GTkF/potXX1Ik7Vx,iv:6VZWNSuOGQL3FTOaHkTwhZ+lpnflN3w6T5jvlXxXGFE=,tag:tpsGYH23ZbHWWFiNxjENnA==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:rvuwC2hzaMED7969,iv:fCGX3OZcwEa7M6ZDn8cdbyQMdpdjE+ggpUa38/GN69w=,tag:jwoteTPj4Z6F5O0aLsBuNA==,type:str]
    STORAGE_DOMAIN: ENC[AES256_GCM,data:lyxWufPGGOJl4W4UDg==,iv:kzkvcUeAOFWhERw+nyoIbztkM21PmLE+laVePRlmxxU=,tag:hSSLIxHeXKEiurw5c3aDHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kl8w06hq4gdg3sutffnnu2nwwjx969p3ll2wguc6aqwpf8f8ny0sq6ztqx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5K2E2Szh0TFFFODJLckNC
            bTc4WEp5UjBCMVU2Rm1xMzBFT2xZUlVHOVhJCmxoZlF1OWpGc2V5ZTdqTnpJRjVS
            Vm45cHJpK2VzS3ZSQ0kxRWpMakJSNEEKLS0tIGxoQWdudE5ZcnNELy9QNmxzajEx
            c2YxZDRGbTFoVWZyalg2T0QwejQ4RW8KbV1PFZhM78QQwVgxrDqqd07NkbNYs++J
            nOZtwl7ebhYmZcZiGn1/kNd2/N0wow9SRNDnQHXSPH9KrUFmHhMNMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-05T18:15:39Z"
    mac: ENC[AES256_GCM,data:WZWWXwzjDxSiDO5YhvcID1ivqLxqZ378rO/uQqv0V8VHnzu9Pv3hVuXEkQGjb9+AQj6V03DP6wES8T3ZLG/2KXdioGOMrc5KqAhp3dj49xClsmF2/d3r88aaZKrhWGFuNldwNtJ3fvkAVUuMS5FNbquQ71MrgnrP1KHzsavn/Hg=,iv:IPgLcTgor9B596QCh9f986oE2saE6LbGfVAYwZzq164=,tag:2HBbIBCrZHEsGiMEcbHuhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
