apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:pW+kg4xkLivSaUw=,iv:Q6D1NHeevr6VBtpMZsVW6jC1bM81NRqOqvmMKhQIX3A=,tag:iJENPgwbutSpS+BR5KdI7A==,type:str]
    PHYSICAL_DOMAINL: ENC[AES256_GCM,data:Y913WH3DmnZilmnT,iv:1R3NUgli1vYFZo9pDh4WyzvY0uuCNkfY7RR6ZAOdcOY=,tag:NEvOCvPgdHtFKbvIZ1iz3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kl8w06hq4gdg3sutffnnu2nwwjx969p3ll2wguc6aqwpf8f8ny0sq6ztqx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZHE2WVVXQVEvVGZPWnov
            b0dKdFA3NXVQRjJudEQ0UkhiVWdRUVIyT3pBCnhyN25LaFlCcEE5OUh0TWZMNy91
            UGtiQVhIbno5dlU2Zit6K290VUt4Y0kKLS0tIGkyNUMrUW41dHNyZDgwS3FUWkFH
            cExvYTR4d0NOc0txWUlSbHljaDd6R3MK64OB6I2Tetm0FLPaLYhnliXCUob7krHe
            0aNaGvnzNRl+u7xif2HKTw5MTyZxdXNRk4oPWQ7kzCMYYLeLewONxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-24T18:15:58Z"
    mac: ENC[AES256_GCM,data:AF+XDadX7X81zqHO+JSvxLBpqe/jKOdVxDyaY7AIGS792jpWmJAmTOAx6s9digstdAhr0lDVw8u11DI7sQFd25kSyi+aWvOrDDh9k5cycvzunEbFzJ+Tesn/7tQRK/lZXVx3aivIsl/nF6D99l5gMGnuZwGVJD2mdcQe7K0JlT8=,iv:QjUh9e+bueh3YoeHKhsyhlFWYdvlx3NgFCcNkL8O1oQ=,tag:u9w7jJm8jTU9ca/tcju/aQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
