---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/London"
  CLUSTER_CIDR: "20.69.0.0/16"
  NODE_CIDR: "10.20.0.0/24"
  LOADBALANCER_CIDR: "20.20.0.0/16"
