apiVersion: v1
kind: Secret
metadata:
    name: onepassword-token
stringData:
    token: ENC[AES256_GCM,data:gm0GADJwyK0i7M2Ib0n+gIbyHDBOw/RDHrlN7uLHB3KMtE0uwlhrwAh7S+k5j65chjaI1Ik8c1bGtiL1bYz9vgbnzM6/Goc8DNerhrWtoij318z1iwRC0IjMFLRWmzcFyE9pe695o3z4PDvowKAMxORt0h30XKSDAVfJfZMwewAdvtQmjH9hgj9XZSiBJZoGExFjLVRTl6Q/IRarbqVs7ZdIIT8oy5Nm/zxggsifbq9+Cag1xFKZ7ESQ7Ldsok3C2SYv+zY015nPFcc4zgfAI4LJOTIJQS5zO6FH0Y21wwoTqUNRPhcCwnOEDSrJTs5ZvwhvL2vc/+ZrwgdSTcizbtGtANvbzq3/dcYAiFNzxpit0FeMZpQecLPErsZAJV128DdzhRzqJsF5vwHMEm5fzbA/u/Z39MU2AmzTFRS6sNF4raaInF39JvN7I7uCVwex6h4/bQtpYAJIqKiWObfKGrcmY0sIFqtyvL/Itm3MVNKG1yNYeLIwN951Up2G8jGBkV0GsW5g8+mIoKYCamnhUw61hmIsLaM3NVNo+IPm98hPQ/+ImkuGQEbjqp9aZeMM+u1Ep0iSifDtsTJyCtWcdThyr5EV1OLB5UviP94W89ggmskthU7OSW3wbaVGlwQhMBnzihcKu7Mq60VsnSHgycxgAzi4Ao/ufM+515tRqAW0217gHd395i59oQzGDs/hrjOwXHnZsDErZ4bx7wmNK8qjRgjBpETtC692Q8BlWswgD5CEs4zwZIY+GM076mtoHffVObWIQDGIhI6NHCM6ssRAyGGdg54wtycpevSyOUTxVKwaimG8P75Bvp1zcjLj8uCw/Z0BGWWOzZyybrixntpVuw==,iv:r3v5hQsDEKZ5uMzlf6L+AqMkmzQyfV9heRVkBnQd7Nc=,tag:3yLzI8cbrQzzOA/svQKR2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kl8w06hq4gdg3sutffnnu2nwwjx969p3ll2wguc6aqwpf8f8ny0sq6ztqx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6c1lTcVRjWWk5VWpIT0V0
            ZTBYSVVxbFFIWUwwWTBITEVXa2dPZjl5T1FVCjJ0LzhoR3NPWkRwMEZzMUNNOWR3
            aVN0ZnlreS9RdWU5a1NDUGtQQnpIOFEKLS0tIHlMVXpkS0d0bWNrbnc2L1B6dVNH
            MTdlb2t4K2ppbnZXMzdwSFRjRkp0cmcKKOihkiUuP/GF3tTFlHdAcYbKd2lNz6Bx
            +sQDY6+JOKzkJBDoUnLNU4H820fj7UD6WtFPEYZEkpWpiPbFMH97aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-27T16:45:37Z"
    mac: ENC[AES256_GCM,data:Gq0JgslqU9BApgLIs+moYVCDHdSW+JF5Tv4nW58rQCgHOo2RKbD3Chb80x+eJ+GFG8Nrd5JlFSaOd5yEghT7/zAwTH2NaZTAzdBVu9501aV8imKEnF8Xc87JRyw7D5XZWa90IACwDPkA6CGv5+Ovr3onn4xWx+yhrjr59b9bS24=,iv:m6vdg7uo8wmiwy2m94S8emH7fdP6xocHhknzPMRDLaE=,tag:oV2t1bAmEZIG7IJJQrhr/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
