---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.6.0
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultSettings:
      createDefaultDiskLabeledNodes: true
    metrics:
      serviceMonitor:
        enabled: true
    ingress:
      enabled: false
