---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &app paperless
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_DBUSER: "{{ .PAPERLESS_POSTGRES_USERNAME }}"
        PAPERLESS_DBPASS: "{{ .PAPERLESS_POSTGRES_PASSWORD }}"
        PAPERLESS_DBHOST: postgres16-rw.database.svc.cluster.local
        PAPERLESS_DBNAME: paperless
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: >
          {
            "openid_connect": {
              "APPS": [
                {
                  "provider_id": "authentik",
                  "name": "Authentik",
                  "client_id": "{{ .PAPERLESS_OAUTH_CLIENT_ID }}",
                  "secret": "{{ .PAPERLESS_OAUTH_CLIENT_SECRET }}",
                  "settings": {
                  "server_url": "https://authentik.${EXTERNAL_DOMAIN}/application/o/paperless/.well-known/openid-configuration"
                  }
                }
              ],
              "OAUTH_PKCE_ENABLED": "True"
            }
          }
  dataFrom:
    - extract:
        key: paperless
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &app paperless-dbinit
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless-dbinit-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_USER: "{{ .PAPERLESS_POSTGRES_USERNAME }}"
        INIT_POSTGRES_PASS: "{{ .PAPERLESS_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_DBNAME: paperless
        INIT_POSTGRES_SUPER_PASS: "{{.POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: paperless
