---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      homepage:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v0.9.11
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              limits:
                memory: 512Mi

    service:
      app:
        controller: homepage
        ports:
          http:
            port: 3000

    ingress:
      app:
        className: cilium
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
        hosts:
          - host: &host homepage.${CLUSTER_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: homepage-tls-certificate

    serviceAccount:
      create: true
      name: homepage

    persistence:
      config:
        type: configMap
        name: homepage-config
        advancedMounts:
          homepage:
            app:
              - path: /app/config/custom.css
                subPath: custom.css
              - path: /app/config/bookmarks.yaml
                subPath: bookmarks.yaml
              - path: /app/config/kubernetes.yaml
                subPath: kubernetes.yaml
              - path: /app/config/settings.yaml
                subPath: settings.yaml

      secret:
        type: secret
        name: homepage-secret
        advancedMounts:
          homepage:
            app:
              - path: /app/config/services.yaml
                subPath: services.yaml
              - path: /app/config/widgets.yaml
                subPath: widgets.yaml

      logs:
        type: emptyDir
        advancedMounts:
          homepage:
            app:
              - path: /app/config/logs
