---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  KUBECONFORM_SCRIPT: "{{.SCRIPTS_DIR}}/kubeconform.sh"

tasks:

  resources:
    desc: Gather common resources in your cluster, useful when asking for support
    cmds:
      - for: { var: resource }
        cmd: kubectl get {{.ITEM}} {{.CLI_ARGS | default "-A"}}
    vars:
      resource: >-
        nodes
        gitrepositories
        kustomizations
        helmrepositories
        helmreleases
        certificates
        certificaterequests
        ingresses
        pods

  events:
    desc: Get events sorted by modified time
    cmd: kubectl get events -A --sort-by='.metadata.creationTimestamp'

  ns-resources:
    desc: Get all resources in a namespace
    cmd: kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind --ignore-not-found -n {{.ns}}
    requires:
      vars: ["ns"]

  longhorn-annotation:
    desc: Add Longhorn Default Disk annotation
    cmd: "kubectl annotate node {{.node}} --overwrite node.longhorn.io/default-disks-config=[{'path': '/var/lib/longhorn', 'allowScheduling': false}, {'path':'/var/mnt/nvme/longhorn', 'allowScheduling': true}]"
    requires:
      vars: ["node"]

  kubeconform:
    desc: Validate Kubernetes manifests with kubeconform
    cmd: |
      if [ -d "{{.KUBERNETES_DIR}}/flux" ]; then
          bash {{.KUBECONFORM_SCRIPT}} {{.KUBERNETES_DIR}}
      fi
    preconditions:
      - { msg: "Missing kubeconform script", sh: "test -f {{.KUBECONFORM_SCRIPT}}" }

  .reset:
    internal: true
    cmd: rm -rf {{.KUBERNETES_DIR}}
